from django.db import models

# Create your models here.

class Classic(models.Model):
    type = models.CharField(max_length=20)
    eventID = models.CharField(max_length=50, unique=True)
    title = models.TextField()
    startDate = models.DateField()
    endDate = models.DateField()
    location = models.TextField()
    eventStatus = models.CharField(max_length=20)
    locationID = models.CharField(max_length=50)
    performer = models.TextField()
    director = models.TextField()
    address = models.TextField()
    latitude = models.TextField()
    longitude = models.TextField()
    imgUrl = models.TextField()
    timeTable = models.TextField()
    fee = models.TextField()
    age = models.TextField()
    createdAt = models.DateField()
    ticketUrl = models.TextField()

class Musical(models.Model):
    type = models.CharField(max_length=20)
    eventID = models.CharField(max_length=50, unique=True)
    title = models.TextField()
    startDate = models.DateField()
    endDate = models.DateField()
    location = models.TextField()
    eventStatus = models.CharField(max_length=20)
    locationID = models.CharField(max_length=50)
    performer = models.TextField()
    director = models.TextField()
    address = models.TextField()
    latitude = models.TextField()
    longitude = models.TextField()
    imgUrl = models.TextField()
    timeTable = models.TextField()
    fee = models.TextField()
    age = models.TextField()
    createdAt = models.DateField()
    ticketUrl = models.TextField()


class Play(models.Model):
    type = models.CharField(max_length=20)
    eventID = models.CharField(max_length=50, unique=True)
    title = models.TextField()
    startDate = models.DateField()
    endDate = models.DateField()
    location = models.TextField()
    eventStatus = models.CharField(max_length=20)
    locationID = models.CharField(max_length=50)
    performer = models.TextField()
    director = models.TextField()
    address = models.TextField()
    latitude = models.TextField()
    longitude = models.TextField()
    imgUrl = models.TextField()
    timeTable = models.TextField()
    fee = models.TextField()
    age = models.TextField()
    createdAt = models.DateField()
    ticketUrl = models.TextField()

class Complex(models.Model):
    type = models.CharField(max_length=20)
    eventID = models.CharField(max_length=50, unique=True)
    title = models.TextField()
    startDate = models.DateField()
    endDate = models.DateField()
    location = models.TextField()
    eventStatus = models.CharField(max_length=20)
    locationID = models.CharField(max_length=50)
    performer = models.TextField()
    director = models.TextField()
    address = models.TextField()
    latitude = models.TextField()
    longitude = models.TextField()
    imgUrl = models.TextField()
    timeTable = models.TextField()
    fee = models.TextField()
    age = models.TextField()
    createdAt = models.DateField()
    ticketUrl = models.TextField()

class Exhibition(models.Model):
    type = models.CharField(max_length=20)
    eventID = models.CharField(max_length=50, unique=True)
    title = models.TextField()
    startDate = models.DateField()
    endDate = models.DateField()
    location = models.TextField()
    eventStatus = models.CharField(max_length=20)
    locationID = models.CharField(max_length=50)
    performer = models.TextField()
    director = models.TextField()
    address = models.TextField()
    latitude = models.TextField()
    longitude = models.TextField()
    imgUrl = models.TextField()
    timeTable = models.TextField()
    fee = models.TextField()
    age = models.TextField()
    createdAt = models.DateField()
    ticketUrl = models.TextField()

class Concert(models.Model):
    type = models.CharField(max_length=20)
    eventID = models.CharField(max_length=50, unique=True)
    title = models.TextField()
    startDate = models.DateField()
    endDate = models.DateField()
    location = models.TextField()
    eventStatus = models.CharField(max_length=20)
    locationID = models.CharField(max_length=50)
    performer = models.TextField()
    director = models.TextField()
    address = models.TextField()
    latitude = models.TextField()
    longitude = models.TextField()
    imgUrl = models.TextField()
    timeTable = models.TextField()
    fee = models.TextField()
    age = models.TextField()
    createdAt = models.DateField()
    ticketUrl = models.TextField()
